name: NoteDart
version: 0.0.1
description: A sample command-line application.
#author: <Alejandro Sierra Duran> <alejosd5@gmail.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  polymer: any
  paper_elements: any
  redstone: any
  redstone_mapper: any
  shelf_static: any
  mongo_dart_query: any
  redstone_mapper_mongo: any
  async: any
dev_dependencies:
  mock: any
  unittest: '>=0.11.0+5 <0.12.0'
