name: NoteDart
version: 0.0.1
description: A sample command-line application.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  polymer: ">=0.16.0 <0.17.0"
  paper_elements: any
  redstone: any
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  mock: '>=0.11.0+2 <0.12.0'
